### ISSUE TITLE
OpenTTD and OpenRCT2

### ISSUE THREAD

**Issue by r15ch13** [Calinou/scoop-games#1]
Just heard about https://www.openttd.org/ and https://openrct2.org/. I think they would be a good addition. 😄

**Comment by Calinou** [comment]
[I just added OpenTTD](https://github.com/Calinou/scoop-games/commit/9ba6d4a377725c4a526047fb9c0aed72760cf1ac), check it out :smiley:

I'll look at OpenRCT2 later on.

**Comment by r15ch13** [comment]
Found another one: https://endless-sky.github.io/

**Comment by Luckz** [comment]
Do you prefer bumps to older issues regarding for example updating OpenTTD (April had new releases), or new issues for each version?

**Comment by Calinou** [comment]
@Luckz According to the [website downloads page](https://openrct2.org/downloads/releases) and [GitHub releases page](https://github.com/OpenRCT2/OpenRCT2/releases), 0.2.2 is the latest stable version (so the manifest seems to be up-to-date).

If you meant development builds, that could be added in a separate package (like `openrct2-develop`).

**Comment by Luckz** [comment]
OpenTTD, not OpenRCT2 :)

OpenRCT2 has the added question of whether it's easy to integrate with the Steam version of the game; so far my idea was doing symlinks from the game folder to all \openrct2\current\... files and "copying it in" that way, or writing a script to run on update and overwrite the files in the Steam folder.
From what I understand, having Scoop directly handle the RCT2 folder would be slightly dangerous due to having to define every possible file that should not be deleted, etc?
[desired result would be having openrct2.exe replace RCT2.exe in steamapps\common\Rollercoaster Tycoon 2]
