### ISSUE TITLE
iortcw was downgraded from 1.51b to 1.51

### ISSUE THREAD

**Issue by Calinou** [Calinou/scoop-games#11]
It looks like [the automatic updater downgraded iortcw from 1.51b to 1.51](https://github.com/Calinou/scoop-games/commit/bfd3b3c33f612b232a97808c0f332559d97b9115) for no apparent reason. I won't revert this for now, otherwise the automatic updater would likely overwrite it again.

1.51b is the current stable release (it's not marked as a pre-release), see https://github.com/iortcw/iortcw/releases.

Paging @r15ch13 on this, since he maintains the automatic updater :slightly_smiling_face:

By the way, is there an issue with using `\t` in the manifest? Are terminal emulators having trouble displaying it?

**Comment by r15ch13** [comment]
Oh, that probably happened because of the default `github` regex:
https://github.com/lukesampson/scoop/blob/6060d7cb6d83ab0b1d78c8a02e3d2f7a4e45a647/bin/checkver.ps1#L108
Adding a custom regex to `checkver` should solve it:
`"regex": "\/releases\/tag\/(?:v|V)?([\\w.]+)"` (using `\w` instead of `\d`)

`\t` should not be a problem
