### ISSUE TITLE
multimc-dev: Expand-7zipArchive : Cannot validate argument on parameter 'FilePath'

### ISSUE THREAD

**Issue by ROMVoid95** [Calinou/scoop-games#135]
Received this error on multimc-dev game install. ps scripts are one of the few scripting i do not know so sadly i don't have any type of suggestion on a fix. 

```ps
PS C:\Windows\system32> scoop install multimc-dev
Installing 'multimc-dev' (1459) [64bit]
package.tar.gz (13.0 MB) [===//==] 100%
Checking hash of package.tar.gz ... ok.
Extracting package.tar.gz ... Expand-7zipArchive : Cannot validate argument on parameter 'FilePath'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At C:\Users\ROMVoid95\scoop\apps\scoop\current\lib\install.ps1:564 char:13
+             & $extract_fn -Path "$dir\$fname" -DestinationPath "$dir\ ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Expand-7zipArchive], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Expand-7zipArchive
```

**Comment by issaclin32** [comment]
Try `scoop update -f 7zip` to force re-install 7zip.

It seems that the problem is caused by that 7-zip was not installed properly.

![01](https://user-images.githubusercontent.com/27724471/89865064-99a2e180-dbdf-11ea-9e65-e0a26d2ebc4e.png)

![02](https://user-images.githubusercontent.com/27724471/89864973-711ae780-dbdf-11ea-9a10-3f0da958656c.png)

**Comment by ROMVoid95** [comment]
Interesting, 7zip is already installed on the pc so assumed it took from that, but thinking about it this makes more sense.

and yes this fixed the issue
