### ISSUE TITLE
Ryujinx-dev: old version

### ISSUE THREAD

**Issue by RavenMacDaddy** [Calinou/scoop-games#204]
Don't know if it needs to be configured as a nightly, but sadly Ryujinx is not on parity with the version available through the homepage.

For reference, at the time of writing the latest version is 1.0.6635, while the bucket is at 1.0.6604.

Noticed that checkver in the json by TheLastZombie bucket; https://github.com/TheLastZombie/scoop-bucket/blob/master/bucket/ryujinx.json - which _is_ up-to-date - is not using "replace": "${2}" in comparison.

Otherwise checkver and autoupdate seem to be identical between the two - could that be interfering?

Thanks in advance.

**Comment by BlackPowerade** [comment]
TheLastZombie's bucket and this bucket received the same commit for ryujinx 1.0.6659 within 1 hour of each other. 
   https://github.com/Calinou/scoop-games/commit/b25a3af5a4966d3fe9824641f51a6404b7bac619  
   https://github.com/TheLastZombie/scoop-bucket/commit/f7f3c1546cad8fcbd5bc4cf8e7a7e11edc8f6e49    
it looks like the update bots might be slightly out of sync.

As for the `${2}`, it must have slipped my mind. The checkver doesn't actually need it since scoop automatically replaces whatever is captured by `(?<version>.*?)`, `${2}` functionally does the same thing in this situation.

**Comment by RavenMacDaddy** [comment]
Just saw that incidentally.

Not sure what caused practically skipping a version per se, but I'm glad to see it working as intended at the moment.

Any idea what might be the reason for that behavior?

**Comment by BlackPowerade** [comment]
The checkver works by fetching the latest build from appveyor, which the ryujinx download links mirror. If the manifest update bot runs at say 12pm and finds the build 1.0.XXXX it will use that. But if ryujinx gets a commit at say 2pm, appveyor will generate a new build 1.0.YYYY, and the ryujinx download links will mirror that. Causing the scoop manifest and the ryujinx site to possibly be out of sync.

This used to be huge issue with `mgba-dev`, as there was only one link to get the latest build, and at least to my knowledge no way to get previous builds. Meaning the manifest bot would update, mgba would get a new build an hour or 2 later, and then scoop would throw an error about hash mismatching when someone would attempt to update or install.

**Comment by RavenMacDaddy** [comment]
I see, thank you for the explanation.
