### ISSUE TITLE
(Request) add heroic-game-launcher 

### ISSUE THREAD

**Issue by dtantono** [Calinou/scoop-games#501]
PackageIdentifier: Heroic
PackageVersion: 1.8.2
PackageLocale: en-US
Publisher: flavioislima
PackageName: Heroic-game-launcher
License: open source
ShortDescription: open source epic game client
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v1.8.2/Heroic.Setup.1.8.2.exe
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by couleurm** [comment]
Hey, made a manifest for my own [bucket](https://github.com/couleur-tweak-tips/utils/tree/main/bucket) (that I haven't pushed yet), I feel like it would fit more here, feel free to add it (or I'll push it to mine)

I'm using 7z in the pre_install because Heroic.exe is an archive which contains in itself a .7z archive, which actually contains what needs to be extracted (I couldn't make `extract_to` work)
```json
{
    "version": "2.0.2",
    "url": "https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v2.0.2/Heroic-2.0.2.exe#dl.7z",
    "homepage": "https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher",
    "license": {
        "identifier": "GPL-3.0",
        "URL": "https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/main/COPYING"
    },
    "extract_dir": "$PLUGINSDIR",
    "bin": "Heroic.exe",
    "shortcuts": [
        [
            "Heroic.exe",
            "Heroic"
        ]
    ],
    "pre_install": "7z e \"$dir\\app-64.7z\" -o\"$dir\" -y",
    "checkver": {
        "autoupdate": "github",
        "url": "https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/$ver/Heroic-$ver.exe#dl.7z"
    }
}
```

**Comment by dtantono** [comment]
you can push your own bucket

**Comment by Zliced13** [comment]
Hello I fixed the manifest and did another PR based on this issue.
